### ISSUE TITLE
Allow float ranges

### ISSUE THREAD

**Issue by ghost** [braiden-vasco/lita-random#14]
If arguments provided for commands `random <to>` and `random <from> <to>` are floating point numbers then generate floating point number too. See [Random#rand](http://ruby-doc.org/core-2.0.0/Random.html#method-i-rand).

Examples:

```
You: lita random 1.5
Lita: 0.10797082105354522
You: lita random 5.0 10.0
Lita: 9.029069844543358
```

**Comment by braiden-vasco** [comment]
closed in #16 and #17
